name: pep-8_check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest  # ОС для запуска
    steps:
    - uses: actions/checkout@v4  # клонирование репозитория
    - uses: actions/setup-python@v4  # установка python
      with:
        python-version: "3.11"
    - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: pip install pycodestyle
    - run: pycodestyle lab4/*.py
