name: pep-8_check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest  # ОС для запуска
    steps:
    - uses: actions/checkout@v4  # клонирование репозитория
      with:
        fetch-depth: 0  # полная история (нужна для новых файлов)
    - uses: actions/setup-python@v4  # установка python
      with:
        python-version: "3.11"
    - run: ls -R
    - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: pip install pycodestyle
    - run: pycodestyle *.py
